**Problem 1**

In [14]:
import torch
import random
import time

In [15]:
def random_generate_data(positvie_num_need, negative_num_need):
  # line equation y=mx+b
  m = 0.7
  b = 0.3

  # Generate 30 random 2D data samples
  data = []
  current_positive_num = 0
  current_negative_num = 0

  while len(data) < positvie_num_need + negative_num_need:
      x = random.uniform(-10, 10) # Uniformly generate a random x value between -10 and 10
      y = random.uniform(-10, 10) # Uniformly generate a random y value between -10 and 10
      w = torch.tensor([m, -1, b]) # mx - y + b = 0
      X = torch.tensor([x, y, 1])
      label = -1
      # mark the sample as positive (1) or negative (-1)
      if torch.dot(w, X) > 0 and current_positive_num < positvie_num_need:
        label = 1
        current_positive_num += 1
        data.append(torch.tensor([x, y, label]))
      elif torch.dot(w, X) < 0 and current_negative_num < negative_num_need:
        label = -1
        current_negative_num += 1
        data.append(torch.tensor([x, y, label]))
  
  # Shuffle the data
  random.shuffle(data)

  # Split the data into positive and negative samples
  # [sample[:2] for sample in data if sample[2] == 1][:15] is a list comprehension in Python 
  # that extracts the first two elements of the tuples in the data list where the third element 
  # (i.e., sample[2]) is equal to 1 (i.e., positive samples), and then selects the first 
  # 15 elements of the resulting list.
  positive_samples = [sample[:3] for sample in data if sample[2] == 1][:positvie_num_need]
  negative_samples = [sample[:3] for sample in data if sample[2] == -1][:negative_num_need]

  # Print the positive and negative samples
  print("Length of data:", len(data))
  print("Number of positive samples: ", len(positive_samples))
  print("Number of negative samples: ", len(negative_samples))
  print("Positive samples:" + str(positive_samples))
  print("Negative samples:" + str(negative_samples))
  print("Data:", data)
  return data

In [16]:
random_generate_data(15, 15)

Length of data: 30
Number of positive samples:  15
Number of negative samples:  15
Positive samples:[tensor([-0.7156, -5.0919,  1.0000]), tensor([ 7.4689, -0.5929,  1.0000]), tensor([ 1.2246, -9.4216,  1.0000]), tensor([ 4.0174, -7.8684,  1.0000]), tensor([7.6470, 5.6506, 1.0000]), tensor([-6.1422, -8.8320,  1.0000]), tensor([ 6.2420, -3.0070,  1.0000]), tensor([ 1.4200, -6.6047,  1.0000]), tensor([ 9.3472, -1.0342,  1.0000]), tensor([ 2.3557, -4.2660,  1.0000]), tensor([-0.2953, -4.6959,  1.0000]), tensor([-2.5392, -4.2677,  1.0000]), tensor([-4.0828, -9.0508,  1.0000]), tensor([ 0.8390, -1.0549,  1.0000]), tensor([4.8597, 2.0477, 1.0000])]
Negative samples:[tensor([-6.2466,  3.2732, -1.0000]), tensor([-2.6870,  2.0135, -1.0000]), tensor([-5.8922, -3.7425, -1.0000]), tensor([-0.2712,  3.1782, -1.0000]), tensor([-4.2756,  5.3413, -1.0000]), tensor([-5.2952, -2.6869, -1.0000]), tensor([ 5.0561,  6.8915, -1.0000]), tensor([-4.4267,  9.1804, -1.0000]), tensor([-3.6379,  9.3189, -1.0000]),

[tensor([-6.2466,  3.2732, -1.0000]),
 tensor([-2.6870,  2.0135, -1.0000]),
 tensor([-0.7156, -5.0919,  1.0000]),
 tensor([-5.8922, -3.7425, -1.0000]),
 tensor([ 7.4689, -0.5929,  1.0000]),
 tensor([ 1.2246, -9.4216,  1.0000]),
 tensor([-0.2712,  3.1782, -1.0000]),
 tensor([ 4.0174, -7.8684,  1.0000]),
 tensor([7.6470, 5.6506, 1.0000]),
 tensor([-6.1422, -8.8320,  1.0000]),
 tensor([-4.2756,  5.3413, -1.0000]),
 tensor([ 6.2420, -3.0070,  1.0000]),
 tensor([-5.2952, -2.6869, -1.0000]),
 tensor([ 5.0561,  6.8915, -1.0000]),
 tensor([ 1.4200, -6.6047,  1.0000]),
 tensor([ 9.3472, -1.0342,  1.0000]),
 tensor([ 2.3557, -4.2660,  1.0000]),
 tensor([-4.4267,  9.1804, -1.0000]),
 tensor([-0.2953, -4.6959,  1.0000]),
 tensor([-2.5392, -4.2677,  1.0000]),
 tensor([-4.0828, -9.0508,  1.0000]),
 tensor([-3.6379,  9.3189, -1.0000]),
 tensor([-1.9940,  6.5141, -1.0000]),
 tensor([-8.1995,  2.9455, -1.0000]),
 tensor([-8.1823,  1.9785, -1.0000]),
 tensor([ 3.0408,  9.7971, -1.0000]),
 tensor([ 8.259

**Problem 2**


In [17]:
def PLA(data,w0):
  w = w0 
  iterations = 0
  while True:
    num_errors = 0
    for elements in data:
      x, y, label = elements
      if compare(w, x, y, label): #check if less than zero
        w = w + label * torch.tensor([x, y, 1])
        num_errors += 1
    iterations += 1
    if num_errors == 0:
      break
  return w, iterations


In [18]:
def compare(w, x, y, label):
  return True if label * torch.dot(w,torch.tensor([x, y, 1], dtype=torch.float32)) <= 0 else False

In [19]:
w0 = torch.tensor([1, 1, 1], dtype=torch.float32)
data = random_generate_data(15, 15)
w, iterations = PLA(data, w0)
print("Number of iterations:", iterations)
print("Final weight:", w)

Length of data: 30
Number of positive samples:  15
Number of negative samples:  15
Positive samples:[tensor([ 3.7156, -5.9290,  1.0000]), tensor([ 7.6657, -4.3772,  1.0000]), tensor([ 8.4764, -9.1511,  1.0000]), tensor([ 0.5109, -1.8167,  1.0000]), tensor([ 5.7449, -3.5024,  1.0000]), tensor([-9.0592, -9.5030,  1.0000]), tensor([7.4542, 4.9384, 1.0000]), tensor([-9.4200, -7.0116,  1.0000]), tensor([ 5.3537, -7.7933,  1.0000]), tensor([-4.7427, -8.1540,  1.0000]), tensor([9.9357, 2.0097, 1.0000]), tensor([ 3.7036, -4.6560,  1.0000]), tensor([-2.9877, -8.8984,  1.0000]), tensor([-2.3826, -7.6997,  1.0000]), tensor([ 2.8159, -2.8000,  1.0000])]
Negative samples:[tensor([-9.0339,  9.8745, -1.0000]), tensor([ 3.4287,  5.2814, -1.0000]), tensor([-6.7789,  0.0368, -1.0000]), tensor([ 1.5831,  2.8007, -1.0000]), tensor([-7.4465,  9.9905, -1.0000]), tensor([-2.7267,  3.5317, -1.0000]), tensor([ 2.5596,  3.0661, -1.0000]), tensor([-8.1119,  0.5133, -1.0000]), tensor([-4.3967,  0.6238, -1.0000]),

In [20]:
iterations_sum = 0
average_iterations = 0
for i in range(3):
  data = random_generate_data(15, 15)
  w0 = torch.tensor([1, 1, 1], dtype=torch.float32)
  w, iterations = PLA(data, w0)
  iterations_sum += iterations

average_iterations = iterations_sum / 3
print("=================================================================")
print("Average number of iterations when PLA halts: ",average_iterations)

Length of data: 30
Number of positive samples:  15
Number of negative samples:  15
Positive samples:[tensor([-0.0156, -2.9897,  1.0000]), tensor([-3.2189, -5.5784,  1.0000]), tensor([-0.9331, -9.5328,  1.0000]), tensor([2.6970, 1.1557, 1.0000]), tensor([ 1.2982, -4.8949,  1.0000]), tensor([ 3.2083, -5.8162,  1.0000]), tensor([-3.4872, -5.0683,  1.0000]), tensor([ 0.8329, -2.9519,  1.0000]), tensor([-1.7813, -4.9761,  1.0000]), tensor([9.3737, 3.7618, 1.0000]), tensor([8.8248, 1.8391, 1.0000]), tensor([5.7444, 2.3761, 1.0000]), tensor([ 3.2801, -4.1942,  1.0000]), tensor([-2.1424, -7.9917,  1.0000]), tensor([ 1.5966, -9.7630,  1.0000])]
Negative samples:[tensor([-2.5730, -0.6185, -1.0000]), tensor([-6.2787, -0.6020, -1.0000]), tensor([ 8.6012,  7.3098, -1.0000]), tensor([-2.8730,  2.6924, -1.0000]), tensor([ 2.5832,  7.4640, -1.0000]), tensor([-4.0722,  7.3901, -1.0000]), tensor([ 4.1806,  4.7906, -1.0000]), tensor([-1.8681,  2.5079, -1.0000]), tensor([-4.7027,  6.4847, -1.0000]), tenso

**Problem 3**

In [21]:
# generating 1000 positive samples and 1000 negative samples
data = random_generate_data(1000, 1000)

Length of data: 2000
Number of positive samples:  1000
Number of negative samples:  1000
Positive samples:[tensor([ 9.6682, -9.2766,  1.0000]), tensor([-3.2372, -8.9010,  1.0000]), tensor([-2.6852, -7.1644,  1.0000]), tensor([ 1.2332, -2.8182,  1.0000]), tensor([-0.4895, -2.1026,  1.0000]), tensor([-5.2337, -4.3281,  1.0000]), tensor([-1.4109, -2.5728,  1.0000]), tensor([-2.6456, -9.8580,  1.0000]), tensor([9.6953, 2.5604, 1.0000]), tensor([ 3.7781, -4.3276,  1.0000]), tensor([ 1.1501, -1.4532,  1.0000]), tensor([ 9.3408, -1.6662,  1.0000]), tensor([7.2951, 3.5695, 1.0000]), tensor([6.9992, 1.3954, 1.0000]), tensor([ 0.1107, -1.7815,  1.0000]), tensor([ 2.5212, -7.5311,  1.0000]), tensor([3.5685, 0.9987, 1.0000]), tensor([7.3035, 0.8855, 1.0000]), tensor([4.7996, 3.0931, 1.0000]), tensor([-2.3902, -3.7984,  1.0000]), tensor([-8.8652, -7.7086,  1.0000]), tensor([ 7.4081, -2.1782,  1.0000]), tensor([ 8.2661, -2.4353,  1.0000]), tensor([ 8.2856, -1.8873,  1.0000]), tensor([ 8.4370, -2.115

In [22]:
def error_rate(data, w):

  num_errors = 0

  for elements in data:
    x, y, label = elements
    if compare(w, x, y, label): #check if less than zero
      w = w + label * torch.tensor([x, y, 1])
      num_errors += 1

    
  return num_errors / len(data), w

In [23]:
# Pocket Algorithm
def pocket_algorithm(data, num_iterations):
  w_current = torch.tensor([0, 0, 0], dtype=torch.float32)
  w_pocket = torch.tensor([0, 0, 0], dtype=torch.float32)
  error_current = 0
  error_pocket = 1
  random_data_points = random.sample(data, random.randint(1, len(data))) 
  

  for i in range(num_iterations):
    error_current, w_current= error_rate(random_data_points, w_current)
    if error_current <= error_pocket:
      error_pocket = error_current
      w_pocket = w_current

  return w_pocket, error_pocket



In [24]:
tic = time.process_time()
w0 = torch.tensor([0, 0, 0], dtype=torch.float32)
PLA(data,w0)
toc = time.process_time()
print (" ----- PLA Computation Time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
w_pocket, error_pocket = pocket_algorithm(data, 100) # set to run 100 times
toc = time.process_time()
print (" ----- Pocket Algorithm Computation Time = " + str(1000*(toc - tic)) + "ms")

 ----- PLA Computation Time = 284.82463499999966ms
 ----- Pocket Algorithm Computation Time = 164.2825419999987ms


**Problem 4**

In [25]:
def making_mislabeled_data(mislabeled_to_positive_need, mislabeled_to_negative_need):
  # line equation y=mx+b
  m = 0.7
  b = 0.3

  # Generate 30 random 2D data samples
  data = []
  current_mislabeled_positive_num = 0
  current_mislabeled_negative_num = 0

  while len(data) < mislabeled_to_positive_need + mislabeled_to_negative_need:
      x = random.uniform(-10, 10) # Uniformly generate a random x value between -10 and 10
      y = random.uniform(-10, 10) # Uniformly generate a random y value between -10 and 10
      w = torch.tensor([m, -1, b]) # mx - y + b = 0
      X = torch.tensor([x, y, 1])
      label = -1
      # mark the sample as positive (1) or negative (-1)
      if torch.dot(w, X) > 0 and current_mislabeled_positive_num < mislabeled_to_positive_need:
        label = - 1
        current_mislabeled_positive_num += 1
        data.append(torch.tensor([x, y, label]))
      elif torch.dot(w, X) < 0 and current_mislabeled_negative_num < mislabeled_to_negative_need:
        label = 1
        current_mislabeled_negative_num += 1
        data.append(torch.tensor([x, y, label]))
  
  # Shuffle the data
  random.shuffle(data)

  # Split the data into positive and negative samples
  # [sample[:2] for sample in data if sample[2] == 1][:15] is a list comprehension in Python 
  # that extracts the first two elements of the tuples in the data list where the third element 
  # (i.e., sample[2]) is equal to 1 (i.e., positive samples), and then selects the first 
  # 15 elements of the resulting list.
  mislabeled_to_positive_samples = [sample[:3] for sample in data if sample[2] == -1][:mislabeled_to_positive_need]
  mislabeled_to_negative_samples = [sample[:3] for sample in data if sample[2] == 1][:mislabeled_to_negative_need]

  # Print the positive and negative samples
  print("Length of data:", len(data))
  print("Number of mislebeled to negative samples: ", len(mislabeled_to_positive_samples))
  print("Number of mislebeled to positive samples: ", len(mislabeled_to_negative_samples))
  print("Positive samples:" + str(mislabeled_to_positive_samples))
  print("Negative samples:" + str(mislabeled_to_negative_samples))
  print("Data:", data)
  return data

In [26]:
mislabeled_data = making_mislabeled_data(50, 50)
new_data = random_generate_data(450, 450)
# Add mislabeled data to data
for i in range(len(mislabeled_data)):
  new_data.append(mislabeled_data[i])


# Shuffle the data
random.shuffle(new_data)

w_pocket_mislabeled, error_pocket_mislabeled = pocket_algorithm(new_data, 100) # set to run 100 times
print("=======================================================================================")
print("Accuracy of Pocket Algorithm with misslabeled data: ", 1 - error_pocket_mislabeled)

w_pocket, error_pocket = pocket_algorithm(data, 100) # set to run 100 times
print("Accuracy of Pocket Algorithm with no misslabeled data: ", 1 - error_pocket)

Length of data: 100
Number of mislebeled to negative samples:  50
Number of mislebeled to positive samples:  50
Positive samples:[tensor([-0.8106, -2.7296, -1.0000]), tensor([ 2.5268, -5.9573, -1.0000]), tensor([ 8.1079, -5.9924, -1.0000]), tensor([ 3.7300, -7.7818, -1.0000]), tensor([ 7.4058, -6.6358, -1.0000]), tensor([ 8.5566, -1.8227, -1.0000]), tensor([-0.1344, -0.0600, -1.0000]), tensor([ 9.3520, -3.2909, -1.0000]), tensor([ 7.2506, -4.6434, -1.0000]), tensor([-3.0781, -4.3355, -1.0000]), tensor([ 6.9268, -4.0447, -1.0000]), tensor([-5.1218, -9.5369, -1.0000]), tensor([-0.3549, -7.7289, -1.0000]), tensor([ 4.0054, -3.2763, -1.0000]), tensor([-7.6980, -7.0701, -1.0000]), tensor([ 7.2746, -5.7062, -1.0000]), tensor([ 1.8802, -7.9360, -1.0000]), tensor([ 5.3432, -1.6404, -1.0000]), tensor([ 6.8055,  0.9091, -1.0000]), tensor([ 0.4875, -6.8258, -1.0000]), tensor([-2.7829, -2.1981, -1.0000]), tensor([-3.4722, -7.8102, -1.0000]), tensor([ 0.5280, -5.4793, -1.0000]), tensor([ 9.3190, -5